/**
 * All user-facing text strings in the application.
 */
const L = {
  brand: {
    name: "ԵՍ",
    subtitle: "bolorindem.am",
    adminSubtitle: "bolorindem.am · Ադմին",
    adminMobileTitle: "ԵՍ · Ադմին",
    campaign: "ԵՍ ԲՈԼՈՐԻՆ ԴԵՄ ԵՄ",
    slogan: "Միացիր, քվեարկիր և ստեղծիր փոփոխություններ",
  },
  auth: {
    login: {
      title: "Բարի գալուստ",
      subtitlePhone: "Մուտքագրեք հեռախոսահամարը",
      subtitleEmail: "Մուտքագրեք էլ. փոստը",
      subtitleOtp: "Մուտքագրեք {dest}-ին ուղարկված կոդը",
      phoneLabel: "Հեռախոսահամար",
      phonePlaceholder: "XX XXX XXX",
      emailLabel: "Էլ. փոստ",
      emailPlaceholder: "you@example.com",
      emailInvalid: "Սխալ էլ. փոստ",
      tabPhone: "Հեռախոս",
      tabEmail: "Էլ. փոստ",
      sendCode: "Ուղարկել կոդը",
      otpLabel: "Հաստատման կոդ",
      otpPlaceholder: "000000",
      verify: "Հաստատել",
      backLink: "Հետ",
      codeSent: "SMS-ն ուղարկված է",
      codeSentEmail: "Կոդն ուղարկված է ձեր էլ. փոստին",
      resendCode: "Կրկին ուղարկել",
      resendIn: "Կրկին ուղարկել {sec} վայրկյանից",
      phoneInvalid: "Համարը պետք է լինի 8 թվանշան",
      sessionExpired: "Խնդրում ենք նորից մուտք գործել",
    },
    register: {
      title: "Լրացրեք պրոֆիլը",
      subtitle: "Անունը երևալու է առաջատարների էջում",
      fullNameLabel: "Անուն Ազգանուն",
      fullNamePlaceholder: "Օր.՝ Աննա Սարգիսյան",
      avatarHint: "Ավատարը գեներացվում է ինքնաշխատ",
      submit: "Միանալ",
      sessionExpired: "Խնդրում ենք նորից մուտք գործել",
      saveFailed: "Չհաջողվեց պահպանել",
      welcome: "Բարի գալուստ",
    },
    push: {
      title: "Ծանուցումներ",
      description: "Միացրեք՝ առաջադրանքների մասին իմանալու համար:",
      enable: "Միացնել",
      skip: "Բաց թողնել",
      iosTitle: "Ավելացրեք հավելվածը",
      iosDescription: "iOS-ում ծանուցումների համար ավելացրեք հավելվածը գլխավոր էկրանին:",
      iosStep1a: "Safari-ում սեղմեք",
      iosStep1b: "(Share)",
      iosStep2a: "Ընտրեք «Add to Home Screen»",
      iosStep2b: "",
      iosStep3: "Բացեք հավելվածը գլխավոր էկրանից",
      enabled: "Ծանուցումները միացված են",
      enabledDesc: "Դուք կստանաք կարևոր թարմացումներ",
      denied: "Ծանուցումներն արգելափակված են",
      deniedDesc: "Թույլ տվեք դրանք բրաուզերի կարգավորումներից",
      enableFromProfile: "Միացնել",
    },
  },

  volunteer: {
    dashboard: {
      greeting: "Բարի վերադարձ",
      activeProjects: "Ակտիվ առաջադրանքներ",
      recentActivity: "Վերջին գործողություններ",
      taskCount: "{count} առաջադրանք",
      bonus: "+{points} միավոր",
      emptyProjectsTitle: "Ակտիվ առաջադրանքներ չկան",
      emptyProjectsText: "Ստուգեք ավելի ուշ",
      browseProjects: "Դիտել բոլորը",
      statPoints: "Միավորներ",
      statLeaderboard: "Առաջատարներ",
      statBadges: "Կրծքանշաններ",
      rankDisplay: "{rank} հորիզոնական",
      badgesSection: "Կրծքանշաններ",
      badgesShowAll: "Տեսնել բոլորը",
      badgesEarnFirst: "Ստացիր առաջինդ →",
      startBtn: "Սկսել",
      referralStat: "{count} հրավիրված ընկեր",
      referralIncentive: "Հրավիրեք ընկեր՝ +50 միավոր",
      referralCopyLink: "Կիսվել",
      referralLinkCopied: "Հղումը պատճենված է",
      pushBannerText: "Միացրեք ծանուցումները",
      pushBannerEnable: "Միացնել",
      pushBannerDeniedText: "Ծանուցումներն արգելված են:",
      pushBannerOpenSettings: "Կարգավորումներ",
    },

    projects: {
      title: "Առաջադրանքներ",
      subtitle: "Ակտիվ առաջադրանքներ",
      taskCount: "{count} առաջադրանք",
      emptyTitle: "Ակտիվ առաջադրանքներ չկան",
      emptyText: "Առաջադրանքները կհայտնվեն այստեղ",
      dateFrom: "{date}-ից",
      dateUntil: "Մինչև {date}",
      daysLeft: "{days} օր մնաց",
      lastDay: "Վերջին օրն է",
      heatmapLabel: "Քարտեզ",
    },

    projectDetail: {
      backLink: "Հետ",
      yourProgress: "Ձեր առաջընթացը",
      progressText: "{completed}/{total} առաջադրանք",
      tasksHeading: "Առաջադրանքներ",
      emptyTasks: "Առաջադրանքներ չկան",
    },

    taskDetail: {
      backLink: "Հետ",
      typeStandard: "Ստանդարտ",
      typeForm: "Հարցում",
      typeLocation: "Լոկացիա",
      typePhoto: "Լուսանկար",
      typeDefault: "Առաջադրանք",
      periodDay: "Օրական՝ {limit}×",
      periodWeek: "Շաբաթական՝ {limit}×",
      totalCompletions: "{count} կատ.",
    },

    leaderboard: {
      title: "Առաջատարներ",
      subtitle: "Լավագույն կամավորները",
      me: "Դուք — {name}",
      completions: "{count} կատարում",
      emptyText: "Դեռ մասնակիցներ չկան։ Եղեք առաջինը",
    },

    nav: {
      dashboard: "Գլխավոր",
      projects: "Առաջադրանքներ",
      leaderboard: "Առաջատարներ",
      profile: "Պրոֆիլ",
      voting: "Քվեարկություն",
      elections: "ԱԺ ցուցակ",
      adminSection: "Ադմին",
      adminPanel: "Ադմին վահանակ",
      signOut: "Ելք",
      signedOut: "Դուրս եք եկել համակարգից",
    },

    profile: {
      title: "Պրոֆիլ",
      statPoints: "Միավորներ",
      statRank: "Հորիզոնական",
      statTasksDone: "Արված է",
      recentPoints: "Վերջին միավորները",
      adminPanel: "Ադմին վահանակ",
      badgesTitle: "Կրծքանշաններ",
      badgesEarned: "{count} ձեռք բերված",
      badgeNotEarned: "Դեռ չունեք",
      referralTitle: "Հրավիրեք ընկերներ",
      referralDesc: "Կիսվեք հղումով և ստացեք 50 միավոր:",
      referralCount: "{count} հոգի միացել է ձեր հղումով",
      nameUpdated: "Անունը թարմացվեց",
      nameUpdateError: "Չհաջողվեց թարմացնել",
      recentCompletions: "Վերջին կատարումները",
      bio: "Կենսագրություն",
      bioPlaceholder: "Գրեք ձեր մասին...",
      socialUrl: "Սոց. հղում",
      socialUrlPlaceholder: "https://...",
      socialUrlHint: "Օր.՝ Facebook, Instagram...",
      profileBonusHint: "Լրացրեք ձեր մասին՝ +20 միավոր",
      profileBonusSaved: "Շնորհավոր! +20 միավոր",
      profileSaved: "Պրոֆիլը պահպանված է",
      profileSaveError: "Չհաջողվեց պահպանել",
      socialUrlInvalid: "Սխալ հղում",
      editProfile: "Խմբագրել",
    },

    voting: {
      title: "Քվեարկություն",
      subtitle: "Մասնակցեք և քվեարկեք",
      activeTitle: "Ակտիվ",
      closedTitle: "Ավարտված",
      voteBtn: "Քվեարկել",
      votedLabel: "Քվեարկել եք",
      resultsTitle: "Արդյունքներ",
      totalVotes: "{count} քվե",
      totalVoters: "{count} քվեարկող",
      optionCount: "{count} տարբերակ",
      yourVote: "Ձեր քվեն",
      emptyActive: "Ակտիվ քվեարկություններ չկան",
      emptyClosed: "Ավարտված քվեարկություններ չկան",
      expiresAt: "Ավարտը՝ {date}",
      multiHint: "Ընտրեք մեկ կամ ավելի",
      voteSuccess: "Ձեր քվեն գրանցված է",
      voteError: "Քվեարկությունը ձախողվեց",
      pollClosed: "Քվեարկությունն ավարտված է",
      pollExpired: "Ժամկետն անցել է",
      alreadyVoted: "Արդեն քվեարկել եք",
      pointsForVoting: "միավոր քվեարկության համար",
    }
  },

  admin: {
    nav: {
      dashboard: "Գլխավոր",
      projects: "Նախագծեր",
      users: "Օգտատերեր",
      completions: "Կատարումներ",
      pointGrants: "Միավորներ",
      notifications: "Ծանուցումներ",
      referrals: "Ռեֆերալներ",
      voting: "Քվեարկություն",
      backToApp: "Հավելված",
    },

    notifications: {
      title: "Ծանուցումներ",
      subtitle: "Push ծանուցում բոլորին",
      formTitle: "Նոր ծանուցում",
      formDesc: "Կուղարկվի բոլոր ակտիվ օգտատերերին",
      titleLabel: "Վերնագիր",
      titlePlaceholder: "Նորություն",
      messageLabel: "Հաղորդագրություն",
      messagePlaceholder: "Գրեք տեքստը...",
      urlLabel: "Հղում (ըստ ցանկության)",
      urlHint: "Էջ, որը կբացվի",
      sendBtn: "Ուղարկել",
      sendSuccess: "Ծանուցումն ուղարկված է",
      sendFailed: "Չհաջողվեց ուղարկել",
      recipients: "ստացող",
    },

    dashboard: {
      title: "Ադմին վահանակ",
      subtitle: "Ընդհանուր վիճակագրություն",
      newProject: "Նոր նախագիծ",
      statVolunteers: "Կամավորներ",
      statActiveProjects: "Ակտիվ առաջադրանքներ",
      statCompletionsToday: "Այսօրվա կատարումներ",
      statTotalPoints: "Ընդհանուր միավորներ",
      statPushSubscribers: "Push բաժանորդներ",
      recentCompletions: "Վերջին կատարումները",
      viewAll: "Դիտել բոլորը",
      noCompletions: "Այսօր կատարումներ չկան",
    },

    projects: {
      title: "Առաջադրանքներ",
      subtitle: "Կառավարեք առաջադրանքները",
      newProject: "Նոր նախագիծ",
      taskCount: "{count} առաջադրանք",
      completions: "Կատարումներ",
      edit: "Խմբագրել",
      tasks: "Առաջադրանքներ",
      emptyTitle: "Առաջադրանքներ չկան",
      createFirst: "Ստեղծել առաջին նախագիծը",
      backLink: "Հետ",
      editTitle: "Խմբագրել նախագիծը",
      newTitle: "Նոր նախագիծ",
      newSubtitle: "Ստեղծել նոր նախագիծ",
      tasksSubtitle: "Կառավարել առաջադրանքները",
    },

    tasks: {
      backLink: "Հետ",
      editTitle: "Խմբագրել առաջադրանքը",
    },

    users: {
      title: "Օգտատերեր",
      subtitle: "{count} կամավոր",
      empty: "Օգտատերեր չկան",
    },

    completions: {
      title: "Կատարումներ",
      recordCount: "{count} գրառում",
      recordCountPlural: "{count} գրառում",
      filtered: "(ֆիլտրված)",
      formData: "Տվյալներ →",
      completionNumber: "կատարում #{number}",
      emptyText: "Տվյալներ չկան",
    },

    points: {
      title: "Միավորների հատկացում",
      subtitle: "Միավորների ձեռքով կառավարում",
      grantCardTitle: "Ավելացնել/Հանել միավոր",
      recentGrantsTitle: "Վերջին գործողությունները",
      emptyGrants: "Գործողություններ չկան",
    },

    referrals: {
      title: "Ռեֆերալներ",
      subtitle: "{count} ռեֆերալ",
      topReferrers: "Լավագույն հրավիրողներ",
      allReferrals: "Բոլոր ռեֆերալները",
      referralCount: "{count} ռեֆերալ",
      empty: "Դեռ ռեֆերալներ չկան",
    },

    voting: {
      title: "Քվեարկություն",
      subtitle: "Կառավարեք քվեարկությունները",
      newBtn: "Նոր քվեարկություն",
      newTitle: "Ստեղծել նոր քվեարկություն",
      newSubtitle: "Լրացրեք հարցն ու տարբերակները",
      publish: "Հրապարակել",
      close: "Ավարտել",
      draft: "Սևագիր",
      active: "Ակտիվ",
      closed: "Ավարտված",
      totalVotes: "{count} քվե",
      optionsLabel: "Տարբերակներ",
      addOption: "Ավելացնել",
      removeOption: "Հեռացնել",
      pointsPerVoteLabel: "Միավորներ քվեարկության համար",
      pointsPerVoteHint: "0 = ոչ մի միավոր",
      expiryLabel: "Ավարտը",
      notifyLabel: "Push ծանուցում",
      allowMultiple: "Թույլատրել բազմակի ընտրություն",
      titleLabel: "Հարց",
      descriptionLabel: "Նկարագրություն",
      titlePlaceholder: "Հարցը...",
      descriptionPlaceholder: "Մանրամասներ...",
      optionPlaceholder: "Տարբերակ {n}",
      pollCreated: "Քվեարկությունը ստեղծված է",
      pollPublished: "Քվեարկությունը հրապարակված է",
      pollClosed: "Քվեարկությունն ավարտված է",
      pollDeleteConfirm: "Ջնջե՞լ այս քվեարկությունը",
      pollDeleted: "Քվեարկությունը ջնջված է",
      pollDeleteFailed: "Չհաջողվեց ջնջել",
      deletePoll: "Ջնջել",
      backLink: "Քվեարկություններ",
      emptyTitle: "Քվեարկություններ չկան",
      createFirst: "Ստեղծեք առաջինը",
      voteCount: "{count} քվե",
      pollNotifyTitle: "Քվեարկությանը մնացել է {hours} ժամ",
    }
  },

  forms: {
    project: {
      titleLabel: "Վերնագիր *",
      titlePlaceholder: "Նախագծի անունը",
      titleRequired: "Պարտադիր դաշտ",
      descriptionLabel: "Նկարագրություն",
      descriptionPlaceholder: "Նկարագրություն...",
      statusLabel: "Կարգավիճակ",
      statusDraft: "Սևագիր",
      statusActive: "Ակտիվ",
      statusCompleted: "Ավարտված",
      statusArchived: "Արխիվացված",
      bonusPointsLabel: "Բոնուսային միավորներ",
      startDateLabel: "Սկիզբ",
      endDateLabel: "Ավարտ",
      submitUpdate: "Պահպանել",
      submitCreate: "Ստեղծել",
      deleteConfirm: "Ջնջե՞լ նախագիծը",
      toastUpdated: "Նախագիծը թարմացվեց",
      toastCreated: "Նախագիծը ստեղծվեց",
      toastSaveFailed: "Չհաջողվեց պահպանել",
      toastDeleted: "Ջնջված է",
      toastDeleteFailed: "Չհաջողվեց ջնջել",
    },

    task: {
      titleLabel: "Վերնագիր *",
      titlePlaceholder: "Առաջադրանքի անունը",
      titleRequired: "Պարտադիր դաշտ",
      descriptionLabel: "Նկարագրություն",
      descriptionPlaceholder: "Ի՞նչ պետք է անել...",
      typeLabel: "Տեսակը",
      typeStandard: "Ստանդարտ",
      typeForm: "Հարցում",
      typeLocation: "Լոկացիա",
      typePhoto: "Լուսանկար",
      pointsLabel: "Միավորներ",
      maxPerUserLabel: "Քանակ",
      unlimitedLabel: "Անսահմանափակ",
      activeLabel: "Ակտիվ",
      formFieldsHeading: "Հարցման դաշտեր",
      locationConfigHeading: "Լոկացիայի կարգավորումներ",
      photoHint: "Կամավորը լուսանկարում է առաջադրանքը",
      attachmentsLabel: "Կցված նկարներ (ըստ ցանկության)",
      attachmentsHint: "Կցեք մինչև 5 նկար",
      uploading: "Վերբեռնվում է...",
      downloadBtn: "Ներբեռնել",
      submitUpdate: "Պահպանել",
      submitCreate: "Ստեղծել",
      deleteConfirm: "Ջնջե՞լ առաջադրանքը",
      toastUpdated: "Թարմացված է",
      toastCreated: "Ստեղծված է",
      toastDeleted: "Ջնջված է",
      toastSaveFailed: "Չհաջողվեց պահպանել",
      toastDeleteFailed: "Չհաջողվեց ջնջել",
      periodTypeLabel: "Ժամանակային սահմանափակում",
      periodTypeNone: "Չկա",
      periodTypeDay: "Օրական",
      periodTypeWeek: "Շաբաթական",
      periodLimitLabel: "Առավելագույն քանակ",
      batchSubmissionLabel: "Խմբային կատարում",
    },

    manualGrant: {
      volunteerLabel: "Կամավոր",
      volunteerPlaceholder: "Որոնել...",
      volunteerRequired: "Ընտրեք կամավոր",
      amountLabel: "Միավորներ",
      amountHint: "(բացասական՝ հանելու համար)",
      amountPlaceholder: "Օր.՝ 50 կամ -10",
      amountZeroError: "Չի կարող 0 լինել",
      reasonLabel: "Պատճառ",
      reasonPlaceholder: "Ինչո՞ւ...",
      reasonRequired: "Պատճառը պարտադիր է",
      submit: "Կիրառել",
      toastSuccess: "{amount} միավոր շնորհված է",
      toastFailed: "Չհաջողվեց շնորհել",
    },

    formBuilder: {
      emptyState: "Դաշտեր չկան",
      requiredLabel: "Պարտադիր",
      fieldLabel: "Պիտակ",
      fieldLabelPlaceholder: "Դաշտի անունը",
      typeLabel: "Տեսակ",
      typeText: "Տեքստ",
      typeNumber: "Թիվ",
      typeSelect: "Ընտրություն",
      typeCheckbox: "Checkbox",
      typeLink: "Հղում",
      optionsHeading: "Տարբերակներ",
      addOptionPlaceholder: "Ավելացնել...",
      addOptionBtn: "Ավելացնել",
      addFieldBtn: "Ավելացնել դաշտ",
    },

    locationBuilder: {
      descriptionLabel: "Նկարագրություն",
      descriptionPlaceholder: "Ցուցումներ...",
      targetPointsHeading: "Կետեր",
      pointLabelPlaceholder: "Կետի անունը",
      radiusPlaceholder: "Շառավիղ (մ)",
      latPlaceholder: "Latitude",
      lngPlaceholder: "Longitude",
      maxCheckinsPlaceholder: "Առավելագույնը",
      addPointBtn: "Ավելացնել կետ",
    },
  },

  completion: {
    standard: {
      progressText: "{count}/{max} կատարված է",
      progressTextOnce: "Նշեք՝ ավարտելու համար",
      completeBtn: "Ավարտել (+{points} միավոր)",
      batchLabel: "Քանի՞ անգամ",
      completeBatchBtn: "Ուղարկել {count}× (+{points} միավոր)",
      successTitle: "Ավարտված է",
      successPoints: "+{points} միավոր",
      backToProject: "Հետ",
      alreadyDoneTitle: "Արդեն արված է",
      alreadyDoneText: "Դուք արդեն ստացել եք միավորները",
      allDoneTitle: "Առավելագույնը լրացված է",
      allDoneText: "Այլևս չեք կարող կատարել",
      toastSuccess: "+{points} միավոր",
      toastNetworkError: "Ցանցային սխալ։ Փորձեք կրկին",
    },

    form: {
      cardTitle: "Լրացրեք տվյալները",
      repeatableHint: "({count}/{max})",
      selectPlaceholder: "Ընտրել...",
      validUrlError: "Սխալ URL",
      fieldRequired: "{label} պարտադիր է",
      submitBtn: "Ուղարկել (+{points} միավոր)",
      successTitle: "Ուղարկված է",
      successPoints: "+{points} միավոր",
      backToProject: "Հետ",
      alreadyDoneTitle: "Արդեն ուղարկված է",
      allDoneTitle: "Առավելագույնը լրացված է",
      allDoneText: "Այլևս չեք կարող ուղարկել",
      emptyForm: "Դաշտերը լրացված չեն",
      toastSuccess: "+{points} միավոր",
      toastNetworkError: "Ցանցային սխալ",
      toastFailed: "Չհաջողվեց ուղարկել",
    },

    location: {
      cardTitle: "Հաստատեք լոկացիան",
      repeatableHint: "({count}/{max})",
      batchLabel: "Քանի՞ գրանցում",
      successTitle: "Հաստատված է",
      successPoints: "+{points} միավոր",
      backToProject: "Հետ",
      alreadyDoneTitle: "Արդեն հաստատված է",
      alreadyDoneText: "Դուք ավարտել եք այս առաջադրանքը",
      allDoneTitle: "Առավելագույնը լրացված է",
      allDoneText: "Այլևս հնարավոր չէ",
      emptyConfig: "Լոկացիան սահմանված չէ",
      toastSuccess: "+{points} միավոր",
      toastNetworkError: "Ցանցային սխալ",
      targetLocations: "Վայրեր",
      viewAllOnMap: "Քարտեզում",
      getLocationBtn: "Ֆիքսել դիրքս",
      updateLocationBtn: "Թարմացնել դիրքս",
      confirmBtn: "Հաստատել",
      withinRange: "({distance}մ մոտակայքում)",
      tooFar: "{distance}մ հեռու եք (max {radius}մ)",
      pointFull: "Լրացված է",
    },

    photo: {
      cardTitle: "Ուղարկեք լուսանկար",
      repeatableHint: "({count}/{max})",
      takePhoto: "Լուսանկարել / Ընտրել",
      addPhoto: "Ավելացնել ևս մեկը",
      submitBtn: "Ուղարկել (+{points} միավոր)",
      successTitle: "Ուղարկված է",
      successPoints: "+{points} միավոր",
      backToProject: "Հետ",
      alreadyDoneTitle: "Արդեն ուղարկված է",
      alreadyDoneText: "Դուք ավարտել եք այս առաջադրանքը",
      allDoneTitle: "Առավելագույնը լրացված է",
      allDoneText: "Այլևս չեք կարող ուղարկել",
      toastSuccess: "+{points} միավոր",
      toastUploadFailed: "Վերբեռնումը ձախողվեց",
    },
  },

  filter: {
    allProjects: "Բոլորը",
    searchVolunteer: "Որոնել կամավոր...",
    clear: "Մաքրել",
    noResults: "Ոչինչ չգտնվեց",
  },

 heatmap: {
    // Progress bar
    sloganTitle: "Բոլորին Դեմ Եմ",
    progressDots: "{claimed}/{total} կետ",
    completionBonusPrefix: "Հավելյալ",
    completionBonusSuffix: "բոնուս",
    userStatPrefix: "Ձեր",
    userStatPoints: "{points} մվր ({dots} կետ)",
    userStatBonusEstimate: "(+{bonus})",
    dailyLimitStat: "{used}/10 վերջին 24 ժամում",

    // Info panel
    infoMapTitle: "Քարտեզ",
    infoMapText: "Քարտեզի յուրաքանչյուր կետ իրական GPS տեղորոշում է Երևանում։ Մոտեցեք կետին 20մ շառավղով և սեղմեք «Վերցնել»։",
    infoDotPointsTitle: "Միավորներ",
    infoDotPointsText: "Որքան շատ կետ է հավաքված, այնքան արժեքավոր է հաջորդը՝ {min}-ից (սկզբում) մինչև {max} ({threshold} կետից հետո)։",
    infoBonusTitle: "Ընդհանուր բոնուս՝ {bonus}",
    infoBonusText: "Երբ բոլոր կետերը հավաքվեն, յուրաքանչյուր մասնակից կստանա իր ներդրմանը համապատասխան մասնաբաժին։",
    infoBonusYourShare: "Ձեր ներկայիս բաժինը՝ ~{bonus} միավոր",
    infoBonusIncentive: "Հավաքեք ավելի շատ կետեր՝ ավելի մեծ բոնուս ստանալու համար:",

    // Claim panel
    dotPointValue: "{points} մվր",
    alreadyClaimed: "Արդեն վերցված է",
    claimSuccessPoints: "+{points} միավոր",
    errorTooFar: "{distance}մ հեռավորություն (առավելագույնը՝ {radius}մ)",
    errorGeneric: "Ինչ-որ բան այն չէ",
    errorBanned: "Ձեր հաշիվը արգելափակված է GPS կեղծման կասկածով։",
    errorDailyLimit: "24 ժամում կարող եք վերցնել առավելագույնը 10 կետ։",
    locationDenied: "Տեղադիրքի թույլտվությունը մերժված է։ Կարգավորումներում միացրեք Safari-ի տեղադիրքը։",
    locationUnavailable: "GPS ազդանշան չկա։ Ստուգեք սարքի կարգավորումները։",
    locationTimeout: "Տեղադիրքը ճշտելու ժամանակը սպառվեց։ Կրկին փորձեք։",
    withinRange: "Դուք մոտ եք ({distance}մ)",
    tooFarLocation: "{distance}մ հեռավորություն (առավելագույնը՝ {radius}մ)",
    recenterBtn: "Կենտրոնացնել",
    getLocationBtn: "Ճշտել տեղադիրքը",
    claimingBtn: "Մշակվում է...",
    claimBtn: "Վերցնել (+{points} մվր)",

    // Toasts
    claimToastTitle: "+{points} միավոր",
    claimToastDesc: "Կետը հավաքված է",
    completionToastTitle: "Բոլոր կետերը հավաքված են",
    completionToastDesc: "+{points} + {bonus} բոնուսային միավոր",
  },

  elections: {
    pageTitle: "Ընտրություններ 2026",
    heroTitle: "Խորհրդարանական Ընտրություններ 2026",
    heroSubtitle: "«Բոլորին դեմ եմ» ժողովրդավարական կուսակցության նախընտրական ցուցակ",
    voterGoal: "ընտրող",
    candidateGoal: "թեկնածու",
    goalProgress: "{count} / {goal}",
    goalVoterLabel: "Ընտրողներ",
    goalCandidateLabel: "Թեկնածուներ",
    registerVoter: "Գրանցվել որպես ընտրող",
    registerCandidate: "Գրանցվել որպես թեկնածու",
    voterFeeLabel: "Ընտրողի գրանցման վճար",
    candidateFeeLabel: "Թեկնածուի գրանցման վճար",
    overviewTitle: "Ի՞նչ է անհրաժեշտ",
    overviewSubtitleVoter: "Ընտրողի գրանցում",
    overviewSubtitleCandidate: "Թեկնածուի գրանցում",
    overviewStart: "Սկսել →",
    stepOf: "{step} / {total}",
    nextBtn: "Առաջ",
    backBtn: "Հետ",
    submitBtn: "Վճարել",
    // Step labels
    stepIdentityTitle: "Անձնական տվյալներ",
    fullNameLabel: "Անուն Ազգանուն",
    fullNamePlaceholder: "Օր.՝ Աննա Սարգսյան",
    fullNameRequired: "Լրացրեք անունը",
    documentLabel: "Անձնագիր կամ ՀԾՀ (սոց. քարտ)",
    documentPlaceholder: "Մուտքագրեք փաստաթղթի համարը",
    documentRequired: "Լրացրեք փաստաթղթի համարը",
    phoneLabel: "Հեռախոսահամար",
    phonePlaceholder: "+374 XX XXX XXX",
    stepMovementTitle: "Շարժման մանիֆեստ",
    movementText: "Հաստատում եմ, որ կիսում եմ «ԵՍ ԲՈԼՈՐԻՆ ԴԵՄ ԵՄ» շարժման արժեքներն ու ծրագիրը:",
    acceptMovement: "Ընդունում եմ մանիֆեստը",
    stepCitizenshipTitle: "Քաղաքացիություն և ընտրական իրավունք",
    citizenshipText: "Հաստատում եմ, որ հանդիսանում եմ ՀՀ ընտրական իրավունք ունեցող քաղաքացի:",
    acceptCitizenship: "Հաստատում եմ",
    stepSelfRestrictionTitle: "Ինքնասահմանափակման հայտարարագիր",
    selfRestrictionText: "Ծանոթացել եմ ինքնասահմանափակման պայմաններին և ընդունում եմ դրանք:",
    acceptSelfRestriction: "Ընդունում եմ պայմանները",
    stepAge25Title: "Տարիքային սահմանափակում (25+)",
    age25Text: "Հաստատում եմ, որ լրացել է իմ 25 տարին:",
    acceptAge25: "Հաստատում եմ տարիքս",
    stepOnlyArmenianTitle: "ՀՀ քաղաքացիություն (4 տարի)",
    onlyArmenianText: "Հաստատում եմ, որ վերջին 4 տարում հանդիսացել եմ բացառապես ՀՀ քաղաքացի (չեմ ունեցել այլ երկրի քաղաքացիություն):",
    acceptOnlyArmenian: "Հաստատում եմ",
    stepLivedInArmeniaTitle: "Բնակություն ՀՀ-ում",
    livedInArmeniaText: "Հաստատում եմ, որ վերջին 4 տարում բնակվել եմ ՀՀ-ում (առնվազն 2 տարի):",
    acceptLivedInArmenia: "Հաստատում եմ",
    stepVotingRightTitle: "Ընտրական իրավունք",
    votingRightText: "Հաստատում եմ, որ ունեմ ՀՀ ընտրական իրավունք:",
    acceptVotingRight: "Ունեմ ընտրական իրավունք",
    stepArmenianLanguageTitle: "Հայերենի տիրապետում",
    armenianLanguageText: "Հաստատում եմ, որ տիրապետում եմ հայերենին՝ հաստատված համապատասխան փաստաթղթով:",
    acceptArmenianLanguage: "Հաստատում եմ",
    stepPaymentTitle: "Վճարում",
    paymentInstructions: "Կուղղվեք AmeriaBank-ի վճարային էջ: Վճարումն ավարտելուց հետո կկատարվի ավտոմատ վերադարձ և ձեր գրանցումը կհաստատվի:",
    paymentAmountLabel: "Վճարման ենթակա գումար",
    paymentNote: "Գրանցումը կհաստատվի վճարումը ադմինիստրատորի կողմից ստուգվելուց հետո:",
    successTitle: "Հայտն ընդունված է",
    successSubtitle: "Ձեր հայտը ստեղծված է։ Այն կակտիվանա վճարումը հաստատվելուց հետո։",
    successRef: "Հայտի համարը՝ #{id}",
    duplicateError: "Այս փաստաթղթով հայտ արդեն գոյություն ունի:",
    genericError: "Սխալ տեղի ունեցավ: Խնդրում ենք փորձել կրկին:",
    // Admin
    adminTitle: "Ընտրություններ 2026 — Հայտեր",
    adminSubtitle: "{count} հայտ",
    adminTypeVoter: "Ընտրող",
    adminTypeCandidate: "Թեկնածու",
    adminStatusPending: "Սպասման մեջ",
    adminStatusApproved: "Հաստատված",
    adminStatusRejected: "Մերժված",
    adminPaymentPending: "Չվճարված",
    adminPaymentPaid: "Վճարված",
    dashboardBannerTitle: "2026թ․ Խորհրդարանական Ընտրություններ",
    dashboardBannerText: "Մասնակցիր «Բոլորին դեմ եմ» ժողովրդավարական կուսակցության ցուցակի կազմմանը",
    dashboardBannerBtn: "Գրանցվել հիմա →",
    paymentSuccessTitle: "Վճարումն ընդունված է",
    paymentSuccessBody: "Ձեր գրանցումը հաստատված է։ Շնորհակալություն մասնակցության համար:",
    paymentFailedTitle: "Վճարումը չհաջողվեց",
    paymentFailedBody: "Վճարման ընթացքում խնդիր է առաջացել: Կարող եք կրկին փորձել:",
    backToElections: "← Վերադառնալ",
    tryAgainBtn: "Կրկին փորձել",
    candidatesTitle: "Թեկնածուների ցուցակ",
    candidatesEmpty: "Դեռ գրանցված թեկնածուներ չկան",
    candidateNumber: "#{n}",
  },

  reverseButton: {
    confirm: "Չեղարկե՞լ {points} միավորը",
    label: "Չեղարկել",
    toastFailed: "Չհաջողվեց չեղարկել",
    toastSuccess: "−{points} միավոր",
  },

  bounty: {
    // Projects list section header
    sectionTitle: "Օգտատերերի Բոնուսներ",

    // Create form
    createTitle: "Ստեղծել բոնուս",
    createSubtitle: "Ստեղծեք առաջադրանք, որը կարող է կատարել յուրաքանչյուրը",
    titleLabel: "Վերնագիր *",
    titlePlaceholder: "Ի՞նչ պետք է անել",
    titleRequired: "Պարտադիր է",
    descriptionLabel: "Նկարագրություն *",
    descriptionPlaceholder: "Մանրամասն նկարագրեք...",
    descriptionRequired: "Պարտադիր է",
    proofHintLabel: "Ապացույցի հրահանգ",
    proofHintPlaceholder: "Օր.՝ Ուղարկեք լուսանկար տվյալ վայրից",
    requirePhotoLabel: "Լուսանկար պարտադիր է",
    requirePhotoHint: "Կատարողը պետք է կցի լուսանկար",
    howItWorksTitle: "Ինչպես է աշխատում",
    howItWorksEscrow: "Ստեղծելիս միավորները սառեցվում են. դրանք կազատվեն կատարողին հաստատելուց հետո:",
    howItWorksCancel: "Կարող եք չեղարկել ցանկացած պահի. չկատարված բաժնի միավորները կվերադարձվեն ձեզ:",
    howItWorksDispute: "Եթե ապացույցը կասկածելի է, կարող եք վիճարկել. ադմինը կորոշի արդյունքը:",
    coverImageLabel: "Նկար (ըստ ցանկության)",
    coverImageHint: "Կցեք նկար",
    rewardLabel: "Պարգև (միավոր) *",
    rewardMin: "Նվազագույնը 10 միավոր",
    repeatableLabel: "Բազմակի կատարում",
    repeatableHint: "Յուրաքանչյուր օգտատեր կարող է կատարել մեկ անգամ",
    maxCompletionsLabel: "Կատարողների առավ. քանակ *",
    maxCompletionsMin: "Նվազագույնը 2",
    balanceHintRepeatable: "Հաշ.՝ {balance} մվր · Կսառ.՝ {escrow} մվր ({reward} × {count})",
    expiresLabel: "Ժամկետ (ըստ ցանկության)",
    balanceHint: "Հաշվեկշիռ՝ {balance} մվր · Կսառեցվի {reward} մվր",
    insufficientPoints: "Միավորները չեն բավականացնում",
    submitBtn: "Ստեղծել (−{points} մվր)",
    creating: "Ստեղծվում է...",
    createSuccess: "Բոնուսը ստեղծված է",
    createFailed: "Չհաջողվեց ստեղծել",
    backLink: "Հետ",

    // Bounty detail page
    statusOpen: "Բաց",
    statusClosed: "Ավարտված",
    statusPendingReview: "Ստուգվում է",
    statusAccepted: "Ընդունված",
    statusDisputed: "Վիճարկված",
    statusCancelled: "Չեղարկված",
    statusRejected: "Մերժված",
    postedBy: "Հեղինակ",
    completedBy: "Կատարող",
    reward: "Պարգև",
    rewardPoints: "{points} միավոր",
    expiresAt: "Վերջնաժամկետ՝ {date}",
    expiresAtLabel: "Վերջնաժամկետ",
    proofHintTitle: "Ինչպես ապացուցել",
    mySubmissionTitle: "Իմ ներկայացումը",
    noProofHint: "Ցուցումներ չկան",
    photoEvidenceLabel: "Լուս. ապացույց",
    photoRequired: "Պահանջվում է",
    photoOptional: "Կամընտիր",
    noCompletionsYet: "Դեռ ներկայացված կատարումներ չկան",

    // Complete (target user submits proof)
    completeTitle: "Կատարել առաջադրանքը",
    uploadProofLabel: "Վերբեռնեք ապացույցը",
    uploadProofHint: "Լուսանկար (տեսախցիկ կամ պատկերասրահ)",
    uploadProofOptionalHint: "Կարող եք կցել լուսանկար (ըստ ցանկության)",
    uploadBtn: "Նկարել / Ընտրել",
    uploadBtnOptional: "Կցել լուսանկար (ըստ ցանկության)",
    submitProofBtn: "Ուղարկել ապացույցը",
    submitProofSuccess: "Ապացույցն ընդունված է, {points} մվր շնորհվել է",
    submitProofFailed: "Չհաջողվեց ուղարկել",
    expiredError: "Բոնուսի ժամկետն անցել է",

    // Auto-accept countdown
    autoAcceptIn: "Ինքնաշխատ հաստատում {hours}ժ-ից",
    autoAcceptExpired: "Ինքնաշխատ հաստատումը ակտիվ է",
    pendingReviewHint: "Սպասում է ստուգման",

    // Creator actions
    acceptBtn: "Ընդունել",
    rejectBtn: "Մերժել",
    rejectConfirmYes: "Այո, մերժել",
    disputeConfirmCancel: "Ոչ",
    cancelBtn: "Չեղարկել",
    completionsCount: "{accepted} / {max} կատարված",
    completionsHeader: "Ներկայացված ապացույցներ",
    cancelConfirm: "Չեղարկե՞լ բոնուսը (կվերադարձվի {points} մվր)",
    acceptSuccess: "{points} մվր փոխանցվեց",
    acceptFailed: "Չհաջողվեց հաստատել",
    rejectSuccess: "Ներկայացումը մերժված է",
    rejectFailed: "Չհաջողվեց մերժել",
    cancelSuccess: "{points} մվր վերադարձվեց",
    cancelFailed: "Չհաջողվեց չեղարկել",

    // Results
    submitProofSuccess2: "Ներկայացումն ուղարկված է. սպասեք հաստատմանը",
    acceptedBanner: "Բոնուսը հաստատված է · {points} մվր շնորհվեց",
    rejectedBanner: "Ներկայացումը մերժված է",
    cancelledBanner: "Բոնուսը չեղարկված է",

    // Profile page button
    postBountyBtn: "Ստեղծել բոնուս",

    // Dashboard card
    dashboardTitle: "Բոնուսներ ձեզ համար",
    dashboardDesc: "{count} բաց առաջադրանք · {points} մվր ընդամենը",
    dashboardViewAll: "Տեսնել բոլորը",

    // Bounties list page
    pageTitle: "Բոնուսներ",
    pageSubtitle: "Ստեղծեք կամ կատարեք համայնքի առաջադրանքներ",
    tabOthers: "Բոլոր բոնուսները",
    tabMine: "Իմ բոնուսները",
    sortByReward: "Ըստ պարգևի",
    sortByNewest: "Ըստ ամսաթվի",
    loadMore: "Ավելի շատ",
    noOpenBounties: "Բաց բոնուսներ չկան",
    noMyBounties: "Դուք դեռ չեք ստեղծել բոնուսներ",
    viewAllBounties: "Բոնուսներ",

    // Projects list group labels
    groupCampaign: "Արշավի առաջադրանքներ",
    groupLocation: "Տեղորոշման առաջադրանքներ",
    groupBounties: "Օգտատերերի Բոնուսներ",
    groupMyBounties: "Իմ բոնուսները",
    groupMyCompletedBounties: "Կատարված բոնուսները",
    bountyLabel: "Բոնուս",

    // Admin
    adminTitle: "Բոնուսներ",
    adminSubtitle: "{count} բոնուս",
    adminDisputeResolveAccept: "Հաստատել",
    adminDisputeResolveRefund: "Վերադարձնել հեղինակին",
},
} as const;

export default L;

export function t(template: string, vars: Record<string, string | number>): string {
  return template.replace(/\{(\w+)\}/g, (_, key) => String(vars[key] ?? ""));
}
